/** ICD-10 codes for clinical diagnosis lookup (Kay One seed data). */
const ICD10_CODES = [
  // General / common
  { code: 'M54.5', description: 'Low back pain' },
  { code: 'M51.26', description: 'Other intervertebral disc displacement, lumbar region' },
  { code: 'I10', description: 'Essential (primary) hypertension' },
  { code: 'E11.9', description: 'Type 2 diabetes mellitus without complications' },
  { code: 'J06.9', description: 'Acute upper respiratory infection, unspecified' },
  { code: 'J18.9', description: 'Pneumonia, unspecified organism' },
  { code: 'R50.9', description: 'Fever, unspecified' },
  { code: 'R51', description: 'Headache' },
  { code: 'R10.9', description: 'Unspecified abdominal pain' },
  { code: 'R05.9', description: 'Cough, unspecified' },
  { code: 'R11.0', description: 'Nausea' },
  { code: 'R11.2', description: 'Nausea with vomiting, unspecified' },
  { code: 'K21.9', description: 'Gastro-esophageal reflux disease without esophagitis' },
  { code: 'K29.7', description: 'Gastritis, unspecified' },
  { code: 'N39.0', description: 'Urinary tract infection, site not specified' },
  { code: 'J45.909', description: 'Unspecified asthma, uncomplicated' },
  { code: 'E78.5', description: 'Hyperlipidemia, unspecified' },
  { code: 'F41.9', description: 'Anxiety disorder, unspecified' },
  { code: 'F32.9', description: 'Major depressive disorder, single episode, unspecified' },
  { code: 'M79.1', description: 'Myalgia' },
  { code: 'M25.50', description: 'Pain in unspecified joint' },
  { code: 'S09.90XA', description: 'Unspecified injury of head, initial encounter' },
  { code: 'S61.0', description: 'Open wound of finger without damage to nail' },
  { code: 'T14.90', description: 'Injury, unspecified' },
  { code: 'A09', description: 'Infectious gastroenteritis and colitis, unspecified' },
  { code: 'B34.9', description: 'Viral infection, unspecified' },
  { code: 'Z00.00', description: 'Encounter for general adult medical examination without abnormal findings' },
  { code: 'Z23', description: 'Encounter for immunization' },
  { code: 'O80', description: 'Encounter for full-term uncomplicated delivery' },
  { code: 'O26.9', description: 'Pregnancy-related condition, unspecified' },

  // Dental / oral (Kay One Dental)
  { code: 'K02.9', description: 'Dental caries, unspecified' },
  { code: 'K02.3', description: 'Arrested dental caries' },
  { code: 'K02.51', description: 'Dental caries on pit and fissure surface limited to enamel' },
  { code: 'K02.52', description: 'Dental caries on pit and fissure surface penetrating into dentin' },
  { code: 'K02.61', description: 'Dental caries on smooth surface limited to enamel' },
  { code: 'K02.62', description: 'Dental caries on smooth surface penetrating into dentin' },
  { code: 'K03.0', description: 'Excessive attrition of teeth' },
  { code: 'K03.1', description: 'Abrasion of teeth' },
  { code: 'K03.2', description: 'Erosion of teeth' },
  { code: 'K03.6', description: 'Deposits [accretions] on teeth' },
  { code: 'K03.81', description: 'Cracked tooth' },
  { code: 'K04.0', description: 'Pulpitis' },
  { code: 'K04.1', description: 'Necrosis of pulp' },
  { code: 'K04.4', description: 'Acute apical periodontitis of pulpal origin' },
  { code: 'K04.5', description: 'Chronic apical periodontitis' },
  { code: 'K04.6', description: 'Periapical abscess with sinus' },
  { code: 'K04.7', description: 'Periapical abscess without sinus' },
  { code: 'K05.00', description: 'Acute gingivitis, plaque induced' },
  { code: 'K05.10', description: 'Chronic gingivitis, plaque induced' },
  { code: 'K05.30', description: 'Chronic periodontitis' },
  { code: 'K05.6', description: 'Periodontal disease, unspecified' },
  { code: 'K08.1', description: 'Complete loss of teeth' },
  { code: 'K08.3', description: 'Retained dental root' },
  { code: 'K08.401', description: 'Partial loss of teeth, unspecified cause, class I' },
  { code: 'K08.89', description: 'Other specified disorders of teeth and supporting structures' },
  { code: 'K08.9', description: 'Disorder of teeth and supporting structures, unspecified' },
  { code: 'K09.8', description: 'Other cysts of oral region, not elsewhere classified' },
  { code: 'K12.0', description: 'Recurrent oral aphthae' },
  { code: 'K12.1', description: 'Other forms of stomatitis' },
  { code: 'K13.0', description: 'Diseases of lips' },
  { code: 'K13.70', description: 'Unspecified lesions of oral mucosa' },
  { code: 'K13.79', description: 'Other lesions of oral mucosa' },
  { code: 'K14.0', description: 'Glossitis' },
  { code: 'M26.60', description: 'Temporomandibular joint disorder, unspecified' },
  { code: 'M26.62', description: 'Arthralgia of temporomandibular joint' },
  { code: 'M26.69', description: 'Other specified disorders of temporomandibular joint' },
  { code: 'S02.5', description: 'Fracture of tooth' },
  { code: 'S03.0', description: 'Dislocation of jaw' },
  { code: 'Z01.20', description: 'Encounter for dental examination and cleaning without abnormal findings' },
  { code: 'Z01.21', description: 'Encounter for dental examination and cleaning with abnormal findings' },
  { code: 'Z46.3', description: 'Encounter for fitting and adjustment of dental prosthetic device' },
  { code: 'Z96.5', description: 'Presence of dental prosthetic device' },
  { code: 'Z98.818', description: 'Other dental procedure status' },
];

module.exports = { ICD10_CODES };
